version: '3.8'

services:

  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todolist_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 5


  api:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
        db:
          condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./todolist/:/app/todolist/
      - ./core/:/app/core/
      - ./goals/:/app/goals/


  collect_static:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    command: python manage.py collectstatic -c --no-input
    volumes:
      - django_static:/app/static


  frontend:
    image: sermalenk/skypro-front:lesson-36
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - django_static:/usr/share/nginx/html/static/
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  todolist_pg_data:
    driver: local

  django_static:
    driver: local


