# Generated by Django 4.1.6 on 2023-02-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
